name: Architecture Fitness
favicon: null
layout_spectrum: 0.99551
typography_spectrum: 0.4697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0d182b'
    - '#80c2be'
    - '#e1e1e1'
    - '#fefefe'
  brandStrength: 0.75
  lightness: 0.5606592004187405
  saturation: 0.5
  rhythmicContrast: 0.6288196758832783
purpose: []
