name: Architecture Fitness
favicon: null
layout_spectrum: 0.5667019570246339
typography_spectrum: 0.4328532631043345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5542339917737991
  lightness: 0.5606592004187405
  saturation: 0.979343032464385
  rhythmicContrast: 0.6288196758832783
purpose: []
